/*==========================================
 * Title:  Calculator
 * Author: Borja Delgado
 * .........................................
 * Description:
 * Java program that creates a calculator
 * with add, subtract, multiply and divide
 * using Java Swing elements.
 * ==========================================
 */
package calculator_app;

/**
 *
 * @author borjadelgado
 */
public class calculator extends javax.swing.JFrame {  
    double num, result;
    int select;

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
    }
    
    public void activate() {
        bOnOff.setText("OFF");
        
        tfResult.setText("");
        
        lOperation.setEnabled(true);
        tfResult.setEnabled(true);
        
        b0.setEnabled(true);
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        
        bAdd.setEnabled(true);
        bSub.setEnabled(true);
        bMult.setEnabled(true);
        bDiv.setEnabled(true);
        bResult.setEnabled(true);
        
        bPoint.setEnabled(true);
        bDelete.setEnabled(true);
        bClear.setEnabled(true);
    }
    
    public void deactivate() {
        bOnOff.setText("ON");
        
        lOperation.setText("");
        tfResult.setText("");
        
        lOperation.setEnabled(false);
        tfResult.setEnabled(false);
        
        b0.setEnabled(false);
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
        b5.setEnabled(false);
        b6.setEnabled(false);
        b7.setEnabled(false);
        b8.setEnabled(false);
        b9.setEnabled(false);
        
        bAdd.setEnabled(false);
        bSub.setEnabled(false);
        bMult.setEnabled(false);
        bDiv.setEnabled(false);
        bResult.setEnabled(false);
        
        bPoint.setEnabled(false);
        bDelete.setEnabled(false);
        bClear.setEnabled(false);
    }
    
    public void operation() {
        if (num == 0) {
            
        }
        switch(select){
            case 1: //Add
                result = num + Double.parseDouble(tfResult.getText());
                tfResult.setText(String.format( "%.2f", result ));
                
                break;
            case 2: //Subtract
                result = num - Double.parseDouble(tfResult.getText());
                tfResult.setText(String.format( "%.2f", result ));
                
                break;
                
            case 3: //Multiply
                result = num * Double.parseDouble(tfResult.getText());
                tfResult.setText(String.format( "%.2f", result ));
                
                break;
                
            case 4: //Divide
                result = num / Double.parseDouble(tfResult.getText());
                tfResult.setText(String.format( "%.2f", result ));
                
                break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfResult = new javax.swing.JTextField();
        bDelete = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bSub = new javax.swing.JButton();
        bMult = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bDiv = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bResult = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bPoint = new javax.swing.JButton();
        bOnOff = new javax.swing.JButton();
        lOperation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        tfResult.setEditable(false);
        tfResult.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        tfResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfResult.setName("tfResult"); // NOI18N
        tfResult.addActionListener((evt) -> this.tfResultActionPerformed(evt));

        bDelete.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bDelete.setText("<--");
        bDelete.addActionListener(this::bDeleteActionPerformed);

        bClear.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bClear.setText("C");
        bClear.addActionListener((evt) -> this.bClearActionPerformed(evt));

        bAdd.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bAdd.setText("+");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        b7.setText("7");
        b7.setName("b7"); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        b8.setText("8");
        b8.setName("b8"); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        b9.setText("9");
        b9.setName("b9"); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        bSub.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bSub.setText("-");
        bSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubActionPerformed(evt);
            }
        });

        bMult.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bMult.setText("*");
        bMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMultActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        b4.setText("4");
        b4.setName("b4"); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        b5.setText("5");
        b5.setName("b5"); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        b6.setText("6");
        b6.setName("b6"); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        bDiv.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bDiv.setText("/");
        bDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        b1.setText("1");
        b1.setName("b1"); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        b2.setText("2");
        b2.setName("b2"); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        b3.setText("3");
        b3.setName("b3"); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        bResult.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bResult.setText("=");
        bResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResultActionPerformed(evt);
            }
        });

        b0.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        b0.setText("0");
        b0.setName("b0"); // NOI18N
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        bPoint.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bPoint.setText(".");
        bPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPointActionPerformed(evt);
            }
        });

        bOnOff.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bOnOff.setText("OFF");
        bOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOnOffActionPerformed(evt);
            }
        });

        lOperation.setForeground(new java.awt.Color(255, 0, 0));
        lOperation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lOperation.setName("lOperation"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfResult)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bMult, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bResult, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bSub, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bOnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfResult, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bOnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSub, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMult, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bResult, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResultActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        tfResult.setText(tfResult.getText() + "0");
    }//GEN-LAST:event_button0ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        tfResult.setText(tfResult.getText() + "1");
    }//GEN-LAST:event_button1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        tfResult.setText(tfResult.getText() + "2");
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        tfResult.setText(tfResult.getText() + "3");
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        tfResult.setText(tfResult.getText() + "4");
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        tfResult.setText(tfResult.getText() + "5");
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        tfResult.setText(tfResult.getText() + "6");
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        tfResult.setText(tfResult.getText() + "7");
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        tfResult.setText(tfResult.getText() + "8");
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        tfResult.setText(tfResult.getText() + "9");
    }//GEN-LAST:event_b9ActionPerformed

    private void bOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOnOffActionPerformed
        if(bOnOff.getText() == "ON") {
            activate();
        }
        else deactivate();
    }//GEN-LAST:event_bOnOffActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        tfResult.setText("");
        lOperation.setText("");
        num = 0;
    }//GEN-LAST:event_bClearActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        int opSize = lOperation.getText().length();
        
        if (opSize == 0) {
            if (tfResult.getText().length() != 0) {
                if ( !(tfResult.getText().length() == 1 && tfResult.getText().contains("-")) ) {
                    num = Double.parseDouble(tfResult.getText());
                    lOperation.setText(tfResult.getText() + "+");
                    tfResult.setText("");
                    select = 1;
                }
            }
        }
        else {
            if (tfResult.getText().length() != 0) {
                operation();
                num = Double.parseDouble(tfResult.getText());
                lOperation.setText(tfResult.getText() + "+");
                tfResult.setText("");
                select = 1;
            }
            else {

                String text;

                StringBuilder changeS = new StringBuilder(lOperation.getText());
                changeS.setCharAt(opSize-1, '+');
                text = changeS.toString();
                lOperation.setText(text);
                select = 1;
            }
        }
    }//GEN-LAST:event_bAddActionPerformed

    private void bSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubActionPerformed
        int opSize = lOperation.getText().length();
        
        if (opSize == 0) {
            if ( (tfResult.getText().length() != 0) && !(tfResult.getText().length() == 1 && tfResult.getText().contains("-")) ) {
                num = Double.parseDouble(tfResult.getText());
                lOperation.setText(tfResult.getText() + "-");
                tfResult.setText("");
                select = 2;
            }
            else {
                tfResult.setText("-");
            }
        }
        else {
            if (tfResult.getText().length() != 0) {
                operation();
                num = Double.parseDouble(tfResult.getText());
                lOperation.setText(tfResult.getText() + "-");
                tfResult.setText("");
                select = 2;
            }
            else {
        
                String text;

                StringBuilder changeS = new StringBuilder(lOperation.getText());
                changeS.setCharAt(opSize-1, '-');
                text = changeS.toString();
                lOperation.setText(text);
                select = 2;
            }
        }
    }//GEN-LAST:event_bSubActionPerformed

    private void bMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMultActionPerformed
        int opSize = lOperation.getText().length();
        
        if (opSize == 0) {
            if ( (tfResult.getText().length() != 0) && !(tfResult.getText().length() == 1 && tfResult.getText().contains("-")) ) {
                num = Double.parseDouble(tfResult.getText());
                lOperation.setText(tfResult.getText() + "*");
                tfResult.setText("");
                select = 3;
            }
        }
        else {
            if (tfResult.getText().length() != 0) {
                operation();
                num = Double.parseDouble(tfResult.getText());
                lOperation.setText(tfResult.getText() + "*");
                tfResult.setText("");
                select = 3;
            }
            else {
                String text;

                StringBuilder changeS = new StringBuilder(lOperation.getText());
                changeS.setCharAt(opSize-1, '*');
                text = changeS.toString();
                lOperation.setText(text);
                select = 3;
            }
        }
    }//GEN-LAST:event_bMultActionPerformed

    private void bDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivActionPerformed
        int opSize = lOperation.getText().length();
        
        if (opSize == 0) {
            if ( (tfResult.getText().length() != 0) && !(tfResult.getText().length() == 1 && tfResult.getText().contains("-")) ) {
                num = Double.parseDouble(tfResult.getText());
                lOperation.setText(tfResult.getText() + "/");
                tfResult.setText("");
                select = 4;
            }
        }
        else {
            if (tfResult.getText().length() != 0) {
                operation();
                num = Double.parseDouble(tfResult.getText());
                lOperation.setText(tfResult.getText() + "/");
                tfResult.setText("");
                select = 4;
            }
            else {
                String text;

                StringBuilder changeS = new StringBuilder(lOperation.getText());
                changeS.setCharAt(opSize-1, '/');
                text = changeS.toString();
                lOperation.setText(text);
                select = 4;
            }
        }
    }//GEN-LAST:event_bDivActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        int textSize = tfResult.getText().length();

        if (textSize > 0 && tfResult.getText().toString() != "0") {
            String text;

            StringBuilder retroc = new StringBuilder(tfResult.getText());
            retroc.deleteCharAt(textSize -1);
            text = retroc.toString();
            tfResult.setText(text);
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResultActionPerformed
        if (tfResult.getText().length() == 0) {
            String text;

            StringBuilder retroc = new StringBuilder(lOperation.getText());
            retroc.deleteCharAt(lOperation.getText().length() -1);
            text = retroc.toString();
            tfResult.setText(text);
            lOperation.setText("");
        }
        else if (lOperation.getText().length() != 0){
            operation();
            lOperation.setText(""); 
        }
    }//GEN-LAST:event_bResultActionPerformed

    private void bPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPointActionPerformed
        int textSize = tfResult.getText().length();
        
        if (textSize == 1 && tfResult.getText().contains("-")){
            tfResult.setText("-0.");            
        }
        else if (!tfResult.getText().contains(".")){
            if (textSize == 0) {
                tfResult.setText("0");
            }
            
            tfResult.setText(tfResult.getText() + ".");
        }
    }//GEN-LAST:event_bPointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bPoint;
    private javax.swing.JButton bDiv;
    private javax.swing.JButton bMult;
    private javax.swing.JButton bOnOff;
    private javax.swing.JButton bSub;
    private javax.swing.JButton bResult;
    private javax.swing.JButton bAdd;
    private javax.swing.JLabel lOperation;
    private javax.swing.JTextField tfResult;
    // End of variables declaration//GEN-END:variables
}
